sudo: required

services:
  - docker
  
before_install:
  - docker build -t n42org/freeswitch 1.4

script:
  - docker run --rm n42org/freeswitch /usr/bin/freeswitch -version

notifications:
    email: false
